[build]
  publish = "public"
  [build]
  publish = "public"
  command = "cp public/index-netlify.html public/index.html && echo 'Build complete'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "public"
